name: RemiSux
main: net.yukkuricraft.remisux.RemiSux
version: 0.0.4
api-version: 1.21
author: remiscarlet
softdepend: [DiscordSRV]
commands:
   pong:
      description: Pong
      usage: /pong
   yeet:
     description: Yote
     usage: /yeet <player>

permissions:
  remisux.yeet:
    description: Use the /yeet command
    default: op
  remisux.yeet.bypass:
    description: Bypass (use the -f flag) to yeet people in survival
    default: op
